version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    assignees:
      - "sillen102"